In [1]:
import numpy as np 

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

How to create a boolean array?


In [3]:
np.full((3,3),True,dtype=bool) #full(matrixsize,value,dtype) #create an array with a specified shape and fill it with a given value 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.full((4,4),False,dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

np.full((9),True,dtype=bool).reshape(3,3) # uper vada question ne aa pan lakhi sakay

In [5]:
x= np.array([1,2,3,4])

In [6]:
x

array([1, 2, 3, 4])

How to reshape an array?


In [7]:
arr = np.arange(10)

In [8]:
arr.reshape(2,5) # arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

How to get the common items between two python numpy arrays?

In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [10]:
np.intersect1d(a,b)

array([2, 4])

How to remove from one array those items that exist in another?

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

How to extract all numbers between a given range from a numpy array?

In [12]:
a = np.array([2,6,1,9,10,3,27])
a[(a>5) & (a<=10)]

array([ 6,  9, 10])

how to make a python function that handles scalars to work on numpy arrays?

In [13]:
def max_pair(x,y):
    maximum = [max(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    return np.array(maximum)
a= np.array([5, 7, 9, 8, 6, 4, 5])
b= np.array([6, 3, 4, 8, 9, 7, 1])

max_pair(a,b)

array([6, 7, 9, 8, 9, 7, 5])

How to swap two columns in a 2d numpy array?

In [14]:
arr = np.arange(9).reshape(3,3)
print("Original Array")
arr

Original Array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
print("\nModified Array")
arr[:,[1,0,2]]


Modified Array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

How to swap two rows in a 2d numpy array?

In [16]:
a1 = np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print("\nModified array")
arr[[1,0,2],:]


Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

How to create a 2D array containing random floats between 5 and 10?

In [20]:
rand_arr = np.random.uniform(5,10,(5,3))


In [22]:
rand_arr

array([[9.39489017, 7.78018158, 6.63134973],
       [5.71405452, 5.43025466, 9.38157972],
       [6.70834825, 8.9936265 , 8.42971371],
       [9.61842526, 5.38481687, 7.48994917],
       [5.31909309, 5.11422627, 5.05196015]])

How to print only 3 decimal places in python numpy array?

In [26]:
random_arr = np.random.rand(5,3)
np.set_printoptions(precision=3)

In [27]:
random_arr

array([[0.683, 0.018, 0.963],
       [0.906, 0.279, 0.917],
       [0.523, 0.96 , 0.103],
       [0.984, 0.85 , 0.055],
       [0.195, 0.018, 0.98 ]])

How to limit the number of items printed in output of numpy array?

In [34]:
a = np.arange(15)
np.set_printoptions(threshold=6)

In [35]:
a

array([ 0,  1,  2, ..., 12, 13, 14])