In [1]:
import numpy as np

In [3]:
# Sort , Search & Counting Function.
arr = np.array([4,5,6,7,8,72,34,22,87])

In [4]:
arr

array([ 4,  5,  6,  7,  8, 72, 34, 22, 87])

In [5]:
np.sort(arr) # jya data ne acending order ma sort kari de che 

array([ 4,  5,  6,  7,  8, 22, 34, 72, 87])

In [6]:
np.searchsorted(arr,34) # jya aa data kaya index par jse e dekhadse 

8

In [11]:
arr1 = np.array([1,3,4,5,86,0,0,0,0])

In [15]:
np.count_nonzero(arr1) # jetla non zero element hoi e count karide 

5

In [16]:
arr

array([ 4,  5,  6,  7,  8, 72, 34, 22, 87])

In [18]:
np.where(arr > 6) # jya te data ni index aapse 

(array([3, 4, 5, 6, 7, 8], dtype=int64),)

In [19]:
np.extract(arr>6,arr) # extract e jya > 6 che ene array mathi kadhi nakho 

array([ 7,  8, 72, 34, 22, 87])

In [21]:
# Numpy - Byte Swapping 

In [22]:
arr

array([ 4,  5,  6,  7,  8, 72, 34, 22, 87])

In [24]:
arr.byteswap()  # jya kai pan data nakhyo hase ene byte ma represent kari ne dekhadi dese 

array([  67108864,   83886080,  100663296,  117440512,  134217728,
       1207959552,  570425344,  369098752, 1459617792])

In [25]:
# Numpy - Copies & Views

In [26]:
arr

array([ 4,  5,  6,  7,  8, 72, 34, 22, 87])

In [28]:
a = np.copy(arr) # aane deep copy kahe che 

In [38]:
b = arr.view() # jya view() w shallow copy vadu kam kare che b = arr che 

In [39]:
b

array([67,  5,  6,  7,  8, 72, 34, 22, 87])

In [40]:
arr

array([67,  5,  6,  7,  8, 72, 34, 22, 87])

In [41]:
b[0]= 67

In [42]:
b

array([67,  5,  6,  7,  8, 72, 34, 22, 87])

In [43]:
a

array([ 4,  5,  6,  7,  8, 72, 34, 22, 87])

In [44]:
# Numpy - Matrix Library

In [47]:
import numpy.matlib as nm

In [49]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

matrix is already subclass of array

In [51]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [53]:
# Numpy - Linear Algebra

In [54]:
arr1 = np.random.randint([[2,3],[4,5]])

In [55]:
arr2 = np.random.randint([[5,3],[2,5]])

In [57]:
np.dot(arr1,arr2) # aa dot product kare che

array([[1, 1],
       [1, 1]])

In [59]:
arr1@arr2 # matrix multiplication

array([[1, 1],
       [1, 1]])