=> In them data pass in arrays and matrixes form
=> if you can process the video file or text file in them they endly convert into arrays and matrixes form
=> That is used for the mathematical data
=> at the end of the day in numpy we generate array

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
arr = np.array(l)

In [5]:
type(arr) # where nd means n- dimensional array 

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]]) # this is 2 dimensional array

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l) # asarray function pan aapne array ma provide karine dese 

array([1, 2, 3, 4])

In [8]:
b = np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
a = np.array(l)

In [11]:
a

array([1, 2, 3, 4])

In [12]:
c=a # jy aa same variable ne point kari deche  means aa me te shallow copy thay che 

In [13]:
c

array([1, 2, 3, 4])

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c[0] =100 # jya ama c ma 0 index par change karyu to e change c and a banne ma thay che 

In [16]:
c

array([100,   2,   3,   4])

In [17]:
a

array([100,   2,   3,   4])

In [18]:
d = np.copy(a) # aama jya d ma copy to karavyu pan new location ma karavyu jema deep copy thay che  

In [19]:
d

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
a[1]=200

In [22]:
a

array([100, 200,   3,   4])

In [23]:
d # jo aama d ma change nahi thay 

array([100,   2,   3,   4])

from function e help kare in terms of generating & producing in arrays

In [24]:
np.fromfunction(lambda i,j : i==j,(3,3)) # aama 3,3 e 3 cross 3 matrix banavanu che

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
iterable = (i*i for i in range(5))

In [27]:
np.fromiter(iterable,float) # iterable variable

array([ 0.,  1.,  4.,  9., 16.])

In [28]:
np.fromstring('234 234',sep=" ") # sep means separator jeni help thi tute che and aagad jay che 

array([234., 234.])

In [29]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [30]:
#Numpy- Data Types

In [31]:
l= [2,3,4,5,6]

In [32]:
ar = np.array(l)

In [33]:
ar

array([2, 3, 4, 5, 6])

In [34]:
ar.ndim # ndim means n dimensional thay 

1

In [35]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [36]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
ar2.ndim

2

In [38]:
# have array ni sixe check karvi che to 
ar.size

5

In [39]:
ar2.size

6

In [40]:
ar.shape # aama shape e first row and second column represent kare che 

(5,)

In [41]:
ar2.shape # aama shape e first row and second column represent kare che 

(2, 3)

In [42]:
ar.dtype

dtype('int32')

In [43]:
ar2.dtype

dtype('int32')

In [44]:
ar22 = np.array([(1.4,44,34),(23,44,56)])

In [45]:
ar22

array([[ 1.4, 44. , 34. ],
       [23. , 44. , 56. ]])

In [46]:
ar22.dtype

dtype('float64')

In [47]:
list(range(5)) # jya aama ranve ma aapne floating point number aapi nahi sakiye

[0, 1, 2, 3, 4]

In [48]:
# for solve the floating point number sathe joi tu hoi to arange() no use thay che  means jump karava mate no use thay for float
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [49]:
np.arange(2.3,5.6,.3) # jya jumping karva mate .3 no use karvama aave che 

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [50]:
# je aa data aapyo che ene list ma convert karva mate use thay 
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [51]:
# jya 10 data produce karse in between  1 to 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
# jya aa function array produce karse jema bhadha element ni value 0 hase 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((3,4,2)) # jya 4*2 na 3 matrices ch 

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [54]:
ar4 = np.zeros((3,4,2,3))

In [55]:
ar4.ndim

4

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
on = np.ones((2,3,2))

In [59]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [60]:
on +5 # jya aapne teni satahe karsu to ema bhadhama 5 add kari dese 

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [61]:
on*4 

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [62]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.24474689e+295]])

In [63]:
np.eye(4) # eye means identity matrix thay che 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.linspace(2,4,20) #jya 2,4 vachhe e 20 bhag ma divide karse 

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [65]:
np.logspace(2,5,10, base=2) # jya 2 to 5 vachhe 10 data produced karo

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [66]:
# famous function
Arr = np.random.randn(3,4) # jya avg(mean) e zero hase and standar deviation =1 hase 

In [67]:
import pandas as pd

In [68]:
pd.DataFrame(Arr) 

0         1         2         3
0  0.769239 -0.112975  0.347792 -1.854836
1  0.041920  1.581477  0.457332  0.470280
2  1.300165 -1.171465 -0.541102  1.102660

In [69]:
np.random.rand(3,4)

array([[0.84934788, 0.36191019, 0.62972108, 0.65803996],
       [0.29680471, 0.64071342, 0.39467885, 0.22303117],
       [0.94509334, 0.59422984, 0.12409582, 0.61253589]])

In [70]:
np.random.randint(1,110,(3,4)) # jya e integer j produce karse 

array([[ 57,  43,  96,  62],
       [ 87, 105,  41,  67],
       [ 78,  64, 103,  88]])

In [71]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('test1.csv')

In [72]:
arr = np.random.rand(3,4)

In [73]:
arr

array([[0.58037292, 0.82177354, 0.96468423, 0.58828801],
       [0.47002358, 0.88688151, 0.97145887, 0.11322217],
       [0.00947945, 0.95014701, 0.93865436, 0.39586665]])

In [74]:
arr.reshape(6,2) # jya 6*2 data ne rearrange kari deche 

array([[0.58037292, 0.82177354],
       [0.96468423, 0.58828801],
       [0.47002358, 0.88688151],
       [0.97145887, 0.11322217],
       [0.00947945, 0.95014701],
       [0.93865436, 0.39586665]])

In [77]:
arr1 = arr.reshape(6,-341343434342423)

In [81]:
arr1[1][1]

0.588288009964635

In [82]:
arr1[2:5,1]

array([0.88688151, 0.11322217, 0.95014701])

In [85]:
arr = np.random.randint(1,100,(5,5))

In [87]:
arr[arr>50]

array([75, 75, 98, 93, 93, 83, 98, 95, 71, 58, 61, 59, 98])

In [88]:
arr

array([[75, 75, 98, 45, 18],
       [93, 28, 29, 35, 93],
       [83, 22, 98, 95, 71],
       [58, 61, 42,  3, 16],
       [22, 59, 98, 48, 30]])

In [90]:
arr[2:4,[1,2]]  # jya 2 thi 4 row sudhi jav and column 1 ,2 ma thi data lai lo

array([[22, 98],
       [61, 42]])

In [94]:
arr[0][0] =5000 # jya ahiya data ma reassignment pan thayi sake che 

In [95]:
arr

array([[5000,   75,   98,   45,   18],
       [  93,   28,   29,   35,   93],
       [  83,   22,   98,   95,   71],
       [  58,   61,   42,    3,   16],
       [  22,   59,   98,   48,   30]])

In [99]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [103]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [102]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [105]:
arr1 + arr2 # ahiya e index to index sum karse 

array([[2, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [106]:
arr1 - arr2

array([[ 0, -1, -1],
       [-1,  1, -1],
       [-1,  1, -1]])

In [107]:
arr1 /arr2

array([[1. , 0.5, 0.5],
       [0.5, 2. , 0.5],
       [0.5, 2. , 0.5]])

In [108]:
arr1 * arr2 # jya aa simple index multiplication che 

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [109]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [110]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [112]:
# have jo aapne matrix multiplication karvu hoi to 
arr1@arr2 # jya @ no symbol 

array([[5, 4, 6],
       [7, 5, 8],
       [7, 5, 8]])

In [114]:
arr1/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_17676\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [116]:
arr1 +100

array([[101, 101, 101],
       [101, 102, 101],
       [101, 102, 101]])

In [117]:
arr1 **2

array([[1, 1, 1],
       [1, 4, 1],
       [1, 4, 1]])

In [119]:
# Numpy Broadcasting
arr = np.zeros((4,4))

In [120]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
row = np.array([1,2,3,4])

In [123]:
row

array([1, 2, 3, 4])

In [125]:
arr+row # jya bhdadhi row wisw broadcasting kare  che

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [126]:
np.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'