In [1]:
# Numpy - Array Manipulation.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4)) # jya 1 to 10 ni vachhe data generate karo and 3*4 matrix

In [4]:
arr

array([[6, 1, 6, 5],
       [3, 3, 8, 7],
       [2, 7, 4, 6]])

In [5]:
arr.reshape(6,2)

array([[6, 1],
       [6, 5],
       [3, 3],
       [8, 7],
       [2, 7],
       [4, 6]])

In [7]:
arr.reshape(2,6)

array([[6, 1, 6, 5, 3, 3],
       [8, 7, 2, 7, 4, 6]])

In [9]:
arr.T # jya .T e array ne transpose kari deche 

array([[6, 3, 2],
       [1, 3, 7],
       [6, 8, 4],
       [5, 7, 6]])

In [10]:
arr.flatten() # means array ne flat kari deche 

array([6, 1, 6, 5, 3, 3, 8, 7, 2, 7, 4, 6])

In [11]:
arr1 = np.array([1,2,3,4,5,6])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
arr

array([[6, 1, 6, 5],
       [3, 3, 8, 7],
       [2, 7, 4, 6]])

In [16]:
np.squeeze(arr) 

array([[6, 1, 6, 5],
       [3, 3, 8, 7],
       [2, 7, 4, 6]])

In [17]:
data = np.array([[1],[2],[3]])

In [18]:
data # aama 2 - dimensional ma available che 

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data) # squeeze ni help thi aa one dimensional ma covert thayi jay che 

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4, 5, 6])

In [22]:
np.repeat(arr1,3) # jya aa 3 vakhat repeat kare che 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [24]:
np.roll(arr1,2) # means aa data ne shift kare che etle role kare che 

array([5, 6, 1, 2, 3, 4])

In [26]:
np.diag(arr1) # aama je data hase ene diagonal ma rakhi dese

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [27]:
# Numpy - Binary operation

In [28]:
arr1 = np.random.randint(1,10,(3,4))

In [30]:
arr2 = np.random.randint(1,10,(3,4))

In [31]:
arr1

array([[3, 7, 8, 4],
       [7, 9, 9, 1],
       [4, 7, 8, 5]])

In [32]:
arr2

array([[3, 1, 6, 5],
       [6, 2, 6, 1],
       [7, 1, 2, 6]])

In [33]:
arr1+arr2 # jya index vise e sum kare che  

array([[ 6,  8, 14,  9],
       [13, 11, 15,  2],
       [11,  8, 10, 11]])

In [34]:
arr1 * arr2

array([[ 9,  7, 48, 20],
       [42, 18, 54,  1],
       [28,  7, 16, 30]])

In [35]:
arr1-arr2

array([[ 0,  6,  2, -1],
       [ 1,  7,  3,  0],
       [-3,  6,  6, -1]])

In [36]:
arr1%arr2

array([[0, 0, 2, 4],
       [1, 1, 3, 0],
       [4, 0, 0, 5]])

In [37]:
arr1**arr2

array([[    27,      7, 262144,   1024],
       [117649,     81, 531441,      1],
       [ 16384,      7,     64,  15625]])

In [38]:
arr1 & arr2 # binary operation

array([[3, 1, 0, 4],
       [6, 0, 0, 1],
       [4, 1, 0, 4]])

In [39]:
arr1

array([[3, 7, 8, 4],
       [7, 9, 9, 1],
       [4, 7, 8, 5]])

In [40]:
~arr1  # negate karva mate na operation 

array([[ -4,  -8,  -9,  -5],
       [ -8, -10, -10,  -2],
       [ -5,  -8,  -9,  -6]])

In [42]:
arr1 | arr2

array([[ 3,  7, 14,  5],
       [ 7, 11, 15,  1],
       [ 7,  7, 10,  7]])

In [43]:
arr1>arr2

array([[False,  True,  True, False],
       [ True,  True,  True, False],
       [False,  True,  True, False]])

In [44]:
#Numpy -String  Function
arr =np.array(["sudh","harsh"])

In [45]:
arr

array(['sudh', 'harsh'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['SUDH', 'HARSH'], dtype='<U5')

In [48]:
np.char.title(arr) # jya banne na first letter ne capital kari dese 

array(['Sudh', 'Harsh'], dtype='<U5')

In [50]:
# Numpy - Mathematical Function 
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.98935825, -0.7568025 ],
       [ 0.6569866 ,  0.41211849,  0.41211849,  0.84147098],
       [-0.7568025 ,  0.6569866 ,  0.98935825, -0.95892427]])

In [51]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.14550003, -0.65364362],
       [ 0.75390225, -0.91113026, -0.91113026,  0.54030231],
       [-0.65364362,  0.75390225, -0.14550003,  0.28366219]])

In [52]:
np.tan(arr1)

array([[-0.14254654,  0.87144798, -6.79971146,  1.15782128],
       [ 0.87144798, -0.45231566, -0.45231566,  1.55740772],
       [ 1.15782128,  0.87144798, -6.79971146, -3.38051501]])

In [53]:
np.tanh(arr1)

array([[0.99505475, 0.99999834, 0.99999977, 0.9993293 ],
       [0.99999834, 0.99999997, 0.99999997, 0.76159416],
       [0.9993293 , 0.99999834, 0.99999977, 0.9999092 ]])

In [55]:
np.log(arr1)

array([[1.09861229, 1.94591015, 2.07944154, 1.38629436],
       [1.94591015, 2.19722458, 2.19722458, 0.        ],
       [1.38629436, 1.94591015, 2.07944154, 1.60943791]])

In [56]:
np.exp(arr1)

array([[2.00855369e+01, 1.09663316e+03, 2.98095799e+03, 5.45981500e+01],
       [1.09663316e+03, 8.10308393e+03, 8.10308393e+03, 2.71828183e+00],
       [5.45981500e+01, 1.09663316e+03, 2.98095799e+03, 1.48413159e+02]])

In [57]:
np.sqrt(arr1)

array([[1.73205081, 2.64575131, 2.82842712, 2.        ],
       [2.64575131, 3.        , 3.        , 1.        ],
       [2.        , 2.64575131, 2.82842712, 2.23606798]])

In [59]:
np.power(arr1,2)

array([[ 9, 49, 64, 16],
       [49, 81, 81,  1],
       [16, 49, 64, 25]], dtype=int32)

In [60]:
np.mean(arr1)

6.0

In [62]:
np.median(arr1)

7.0

In [63]:
np.std(arr1) # standard deviation

2.449489742783178

In [64]:
np.var(arr1) # jya e variance thay che 

6.0

In [65]:
np.min(arr1)

1

In [67]:
np.max(arr1)

9